### PR TITLE
Implement Entry API, Rebased #42

### PR DESCRIPTION
**Pull request by dtolnay**
I resolved conflicts between #42 and #53, #54, #57, #59.

### CODE REVIEW

**Comment by FlashCat** [comment]
r? @Gankro

(I've picked a reviewer for you, use r? to override)

**Comment by apasel422** [comment]
Looks good. Could you add a test that calls remove on an `OccupiedEntry` returned from the `Entries` iterator?

**Comment by dtolnay** [comment]
Added.

**Pull request merged**
