### PR TITLE
Release 0.0.10

### PR DESCRIPTION
**Pull request by dtolnay**
This is blocking https://github.com/serde-rs/serde/issues/269

### CODE REVIEW

**Comment by FlashCat** [comment]
r? @apasel422

(I've picked a reviewer for you, use r? to override)

**Comment by apasel422** [comment]
I'll publish to crates.io later on, but how exactly is this blocking that issue?

**Comment by dtolnay** [comment]
Thanks Andrew. The Serde serialization/deserialization for linked-hash-map (#48) was added after the release of 0.0.9, so it has not been in any linked-hash-map release yet. For https://github.com/serde-rs/serde/issues/269 we need a dependency on a map type that preserves insertion order and also has Serde support. We could depend on the linked-hash-map git repo, but I don't think crates.io would let us publish with that dependency.

**Comment by apasel422** [comment]
@dtolnay Right, I'm just wondering why the serde support wasn't implemented in serde itself instead of this crate, then.

**Comment by dtolnay** [comment]
It could have been implemented in serde itself. There was precedent for contain-rs accepting serde implementations (https://github.com/contain-rs/vec-map/pull/15). If you prefer, let's revert #48 and I can move it into serde.

**Comment by apasel422** [comment]
@dtolnay No, that's fine. I just didn't realize that serde was going to be using `linked-hash-map` as a dependency.

**Comment by apasel422** [comment]
0.0.10 is now published on crates.io.

**Pull request merged**
