### PR TITLE
Add front and back methods; pop_* methods return removed values

### LINKED ISSUE #17: Return removed value in pop_front
The method name of `pop_front` is misleading since it does not return the removed value. Changing this would also make the method more useful.

### PR DESCRIPTION
**Pull request by arthurprs**
Fix #17 and paves way for #4.

### CODE REVIEW

**Comment by FlashCat** [comment]
Thanks for the pull request, and welcome! The contain-rs team is excited to review your changes, and you should hear from @huonw (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way Github handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

**Comment by huonw** [comment]
r? @Gankro (I know nothing.)

Sorry for the delay.

**Comment by Gankro** [comment]
LGTM

Thanks!

**Comment by arthurprs** [comment]
@Gankro I think I messed up. Since these don't require the caller to pass the key, all these functions should actually return an Option<(K, V)> instead of the current Option<V>.

**Pull request merged**
