### PR TITLE
Compiles against the Beta channel release

### PR DESCRIPTION
**Pull request by vtnerd**
I'm not sure if this patch is wanted, but it allows LinkedHashMap to compile against the Beta channel release. The changes are somewhat aggressive:
- Removed all features not marked as stable, so that it compiles with beta release
  - Cannot specify hash state during initialization
  - Cannot use ordering trait
- Added `Option` in `LinkedHashMapEntry` to remove unintialized portion, since `unsafe_destructor` is marked as unstable
  - Obviously this adds:
    - `x bytes` of memory for each entry stored, needed by the discriminator in Option. I don't think it can be elided in this case, because its storing a tuple `(Key, Value)`.
    - Runtime checks when retrieving key or value

Might be worth leaving open, in case others need this patch until these features are marked as stable.

### CODE REVIEW

**Comment by FlashCat** [comment]
Thanks for the pull request, and welcome! The contain-rs team is excited to review your changes, and you should hear from @reem (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way Github handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

**Comment by apasel422** [comment]
I think this can be done less drastically. See https://github.com/contain-rs/linked-hash-map/compare/master...apasel422:beta?expand=1

**Comment by apasel422** [comment]
Actually, that code leaks the box itself. Looking into a fix now.

**Comment by apasel422** [comment]
Fixed in https://github.com/contain-rs/linked-hash-map/commit/fc31917a6dab50aa7514714a873cc17194b53ea0.

**Comment by vtnerd** [comment]
Ah crap. I misunderstood the `#![unsafe_destructor]` to mean that a code block cannot have `unsafe` in the drop function. What does that it mean?

**Comment by apasel422** [comment]
Master actually doesn't use unsafe_destructor anymore, as it no longer has
a purpose in Rust. However, you were probably seeing errors related to it
be as there hasn't been a new version pushed to crates.io lately.

**Comment by vtnerd** [comment]
Well that was a bust, might as well drop this request entirely.

But how exactly does the above work? Or more precisely, is this defined anywhere to work as expected? Because transmute seems to just re-classify the bits as another type (like a C-cast), so the pointer now becomes the value inside the `Box`. Which only works if `Box` has a single pointer internally (likely). Is my understanding correct here? I guess this works if you are confident in the internal structure of `Box`.

Anyway, if you look at my patch, you don't need to remove from the box. You can just call .deref() or .deref_mut() when you need a pointer. That removes the need to move in/out of the box at all.

**Comment by reem** [comment]
@vtnerd `Box<T>` is, for all intents and purposes, guaranteed to be represented by a single pointer. A wide body of unsafe code relies on this premise.

**Comment by vtnerd** [comment]
This is a known technique? I thought Rust was trying to reduce the amount of sketchy code typically seen in C/C++, not increase it! It does work, and is unlikely to change internally, but theres not even a strict language/library specification for this (unless I missed it). Just a bit surprised, is all.

**Comment by apasel422** [comment]
This is a known technique. Rust does try to reduce the need for code like this, and such code is expected to be rare in most codebases, but certain data structures require it. The implementations of `{BTreeMap, HashMap}` in `std` use abstractions built upon unsafe code like this.

The unstable `std::boxed::into_raw` and `Box::from_raw` functions provide this behavior without `transmute`, but that is effectively what they are doing under the hood. I'm in favor of reducing the `unsafe`-ness of this crate, but the current implementation mandates this sort of thing. As far as I can tell, Rust's ownership model is not going to permit this data structure to be written without unsafe code or possibly reference counting.

**Comment by Gankro** [comment]
> This is a known technique? I thought Rust was trying to reduce the amount of sketchy code typically seen in C/C++, not increase it!

*in applications*

Libraries, particularly ones building fundamental abstractions (like data structures!) very-much so require `unsafe` code to bootstrap. With `unsafe` code all you could do in Rust is pass around primitives on the stack. You wouldn't be able to allocate things on the heap or call into the OS in any other way. But the key thing is that they expose a safe interface and ideally thoroughly test it. Once that's been done applications can do *whatever they want* and it's not sketchy at all as long as they're not writing `unsafe` (which is indeed rare in application code).

**Comment by vtnerd** [comment]
Theres no memory layout specification for `struct`s in this language, and no specification for the internal storage type of `Box`. I just find it surprising that its deemed acceptable without formal written agreements on the behavior. Obviously its also unlikely that a `Box` will have anything other than a single pointer, and unlikely that the memory layout for a `struct` with a single pointer will have some other memory layout. At this point it sounds like the dev team has defacto decided that `Box` cannot change internally (or many consequences will ensue). Just a convenient trick, that should likely be avoided in user code.

FWIW, the particular unsafe code in question, the `transmute`, isn't needed because the `Box` can hold the memory until the drop anyway. Every place a pointer is needed can simply call the `deref()` and `deref_mut()` on the box, but maybe this is preferred for some reason unknown to me. Does the `Box` type take up more space?

**Comment by apasel422** [comment]
From what I can tell, the reason that the `head` field was made a `*mut` instead of `Box` is `Drop` -- you can't move out of `head` with `fn drop(&mut self)`, so it's impossible to call `mem::forget` on the uninitialized memory in `head.{key, value}`.

In your patch, this isn't an issue, because you're wrapping the key and value in an `Option`. This is obviously a safer approach, but adds space to each allocation and requires calls to `unwrap`, when only the head will ever contain `None`.

It is possible to implement the linked list without a dummy head node (therefore eliminating both the overhead of `Option` and the uninitialized memory), but it complicates the list manipulation code.

**Comment by vtnerd** [comment]
Forgot about the mutability of `self`. A shame. The space for `Option` was unfortunate, but I didn't see any other option considering that I thought `unsafe` code was blocked from use in the destructor.

**Comment by reem** [comment]
If you use `Option<Box<T>>` the overhead should be equivalent to using a nullable `*mut T`, but I haven't dug into this case at all.

**Comment by Gankro** [comment]
@reem this is correct.

**Pull request closed without merging**
