### PR TITLE
Assorted cleanup

### PR DESCRIPTION
**Pull request by apasel422**

### CODE REVIEW

**Comment by Gankro** [comment]
@stepancheg any thoughts?

**Comment by Gankro** [comment]
yesss

**Comment by Gankro** [comment]
@FlashCat r=me 123244

**Comment by FlashCat** [comment]
:scream_cat: `123244` is not a valid commit SHA. Please try again with `ea14dcf`.

**Comment by Gankro** [comment]
:fireworks:

**Comment by Gankro** [comment]
@FlashCat r+

**Comment by FlashCat** [comment]
:pushpin: Commit ea14dcf has been approved by `Gankro`

**Comment by FlashCat** [comment]
:hourglass: Testing commit ea14dcf with merge b5657a1...

**Comment by Gankro** [comment]
@FlashCat r-

**Comment by Gankro** [comment]
@FlashCat r+

**Comment by FlashCat** [comment]
:pushpin: Commit ea14dcf has been approved by `Gankro`

**Comment by Gankro** [comment]
@FlashCat force

**Comment by Gankro** [comment]
I may have broken homu by not having that travis hook setup when I r+'d

**Comment by huonw** [comment]
@FlashCat r-

(whoops)

**Comment by huonw** [comment]
@FlashCat r=Gankro

**Comment by FlashCat** [comment]
:pushpin: Commit ea14dcf has been approved by `Gankro`

**Comment by FlashCat** [comment]
:hourglass: Testing commit ea14dcf with merge 9c4d761...

**Comment by Gankro** [comment]
Whelp, that functionality needs some more ironing out. Maybe another time. For now we can push the merge button like *animals*.

**Pull request merged**
