### PR TITLE
HashMap<KeyRef<K>, *mut LinkedHashMapEntry<K, V>>

### PR DESCRIPTION
**Pull request by dtolnay**
This will make it possible to write a consuming iterator that drops the HashMap but not the data. See https://github.com/contain-rs/linked-hash-map/pull/50#issuecomment-213603050.

### CODE REVIEW

**Comment by FlashCat** [comment]
r? @huonw

(I've picked a reviewer for you, use r? to override)

**Comment by dtolnay** [comment]
Here is a WIP preview of the iterator based on this change: https://github.com/dtolnay/linked-hash-map/pull/1

**Comment by FlashCat** [comment]
:umbrella: The latest upstream changes (presumably #53) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by dtolnay** [comment]
I fixed the merge conflict with #53. The conflicts were in `pop_front`/`front`/`pop_back`/`back`.

**Comment by dtolnay** [comment]
Ping?

**Pull request merged**
